lib/moonshot/cli.rb, lib/moonshot/controller.rb, lib/moonshot/doctor_helper.rb
This resolves acquia/cloud-moonshot#100 by @glennpratt.
=> Ensure that doctor exits non-zero if any checks fail.

lib/moonshot/stack.rb, lib/moonshot/stack_parameter_printer.rb
=> Modified stack.parameters to return a hash similar to stack.outputs.

lib/moonshot/deployment_mechanism/code_deploy.rb
=> Make code deploy role configurable

lib/moonshot/stack.rb
=> Issue #46: Fail if the stack can not be updated within the time limit.

docs/plugins/backup.md, lib/moonshot.rb, lib/plugins/backup.rb, mkdocs.yml, spec/moonshot/plugins/backup_spec.rb
This is rather an initial concept. Please review with extra care.
=> Add backup plugin

.rubocop.yml, docs/plugins/asg_rollout.md, lib/moonshot.rb, lib/moonshot/build_mechanism/script.rb, lib/moonshot/deployment_mechanism/code_deploy.rb, lib/moonshot/shell.rb, lib/moonshot/ssh_command_builder.rb, lib/moonshot/ssh_fork_executor.rb, lib/moonshot/ssh_target_selector.rb, lib/moonshot/stack_asg_printer.rb, lib/moonshot/tools/asg_rollout.rb, lib/moonshot/tools/asg_rollout/asg.rb, lib/moonshot/tools/asg_rollout/asg_instance.rb, lib/moonshot/tools/asg_rollout/hook_exec_environment.rb, lib/moonshot/tools/asg_rollout/instance_health.rb, lib/moonshot/tools/asg_rollout_config.rb, lib/plugins/backup.rb, moonshot.gemspec, spec/moonshot/asg_rollout_spec.rb, spec/moonshot/plugins/backup_spec.rb, spec/moonshot/ssh_spec.rb, spec/moonshot/stub_rollout_asg.rb, spec/spec_helper.rb
This is very close, still a few todos:
=> ASG Rollout tool

lib/moonshot/deployment_mechanism/code_deploy.rb
The raise inside of the step was losing the previous failure message.
=> Fixes #84: Fail CodeDeploy outside of InteractiveLogger Step

lib/moonshot/commands/list.rb, lib/moonshot/stack_list_printer.rb, lib/moonshot/stack_lister.rb
This is a first pass here, we could improve the view more, filter by status, colorize some values, etc.
=> Fixes #141: Make a more detailed environment list.

bin/moonshot, lib/moonshot.rb, lib/moonshot/command_line.rb, lib/moonshot/commands/version.rb
=> Add 'version' command.

docs/1.x-upgrade.md, docs/example.md, docs/index.md, docs/user-guide/cli.md
This is based on #161, I'll rebase on master after that lands. Second commit is doc updates.
=> Docs review

lib/moonshot.rb, lib/moonshot/command_line.rb, lib/moonshot/commands/create.rb, lib/moonshot/commands/list.rb, lib/moonshot/commands/update.rb, lib/moonshot/controller.rb, lib/moonshot/controller_config.rb, lib/moonshot/json_stack_template.rb, lib/moonshot/stack.rb, lib/moonshot/stack_template.rb, lib/moonshot/tools/asg_rollout.rb, lib/moonshot/tools/asg_rollout/asg.rb, lib/moonshot/yaml_stack_template.rb, lib/plugins/backup.rb, moonshot.gemspec
What a breath of fresh air in Ruby... wish I knew about this years ago.
=> Switch to require_all for code loading.

lib/plugins/encrypted_parameters.rb, lib/plugins/encrypted_parameters/kms_key.rb, lib/plugins/encrypted_parameters/parameter_encrypter.rb
This is a plugin we've been developing internally for a while, but has been greatly simplified with the addition of the parameters collection and command line option hooks.
=> Add parameter encryption plugin.

lib/moonshot/deployment_mechanism/code_deploy.rb
=> Fixed nilreference failure in method 'handle_deployment_failure'.

docs/plugins/code_deploy_setup.md, lib/moonshot/creds_helper.rb, lib/moonshot/deployment_mechanism/code_deploy.rb, lib/plugins/code_deploy_setup.rb, spec/moonshot/plugins/code_deploy_setup_spec.rb
New plugin to auto-create any S3 Buckets to be used by CodeDeploy. Also
updates CodeDeploy deploy mechanism to create the IAM Role necessary to
successfully deploy code.
=> CodeDeploySetup plugin

spec/moonshot/commands/build_spec.rb
=> CPD-2351 | Update moonshot for Cloud Database API

.travis.yml, docs/plugins.md, docs/plugins/dynamic_template.md, lib/moonshot/commands/generate_template.rb, lib/moonshot/controller.rb, lib/moonshot/dynamic_template.rb, lib/plugins/dynamic_template.rb, spec/moonshot/dynamic_template_spec.rb
Manual test steps can be found in JIRA.
=> CPD-4444: Added dynamic template command and plugin.

.travis.yml, docs/plugins/dynamic_template.md, lib/moonshot/dynamic_template.rb, spec/moonshot/dynamic_template_spec.rb
CPD-4445: Fix dynamic template plugin issue with reading cli parameters.
=> CPD-4445: Fix dynamic template plugin issue with reading cli parameters.

lib/plugins/rotate_asg_instances/asg.rb
The issue is that the instance that was in outdated_instance array dies off due to health check before we can detach/shutdown it, so I added checks to see the latest state of instance or if there is an error in detaching it as its not in asg  then don’t attempt to shutdown the same instance.
=> CPD-6773: Update asg rotation to check for instance state.

lib/moonshot/stack.rb, lib/plugins/encrypted_parameters.rb, lib/plugins/encrypted_parameters/kms_key.rb
Change: patch
Purpose: maintenance
=> CPD-7696: adding tags for kms keys.

lib/moonshot/build_mechanism/github_release.rb, spec/moonshot/build_mechanism/github_release_spec.rb
**Motivation**
(https://backlog.acquia.com/browse/CPD-8183)
Fixes #NNN
Removed 0.0.0 commit check and using default head check
=> CPD-8183: Removed 0.0.0 commit check

lib/moonshot/build_mechanism/github_release.rb, spec/moonshot/build_mechanism/github_release_spec.rb
=> CPD-8183: Update failing doctor_check_hub_auth.

lib/moonshot/change_set.rb, lib/moonshot/unicode_table.rb
=> PIN-15522 | Rescue Waiter FailureStateError

lib/moonshot/unicode_table.rb
**Motivation**
```
[cloudservicesdev|hosting-dev:prasan2] ~/git/hosting-api$ hosting-api status
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
Using the Central Model for authentication
┌─can't modify frozen String: " " (at /Users/nalaka/git/hosting-api/vendor/bundle/ruby/3.1.0/gems/moonshot-2.0.0.beta7/lib/moonshot/unicode_table.rb:42:in `draw')
Saving session...
...saving history...truncating history files...
...completed.
[cloudservicesdev|hosting-dev:prasan2] ~/git/hosting-api$ 
```
Fixes #NNN
Change the gemfile in hosting-api to have the following changes from my forked repos
```
if …
```
=> PC-17819 | Fix Frozen String Error in Ruby 3.1.3

lib/moonshot/commands/create.rb, lib/moonshot/commands/tag_arguments.rb, lib/moonshot/commands/update.rb, lib/moonshot/controller_config.rb, lib/moonshot/stack.rb, lib/plugins/encrypted_parameters.rb, lib/plugins/encrypted_parameters/kms_key.rb, spec/moonshot/commands/create_spec.rb, spec/moonshot/commands/update_spec.rb, spec/moonshot/stack_spec.rb
=> ORCH-11235 | Port upstream kms tagging changes to master

moonshot.gemspec
=> PC-18071: downgrade moonshot ruby dependency

lib/moonshot/shell.rb, spec/moonshot/shell_spec.rb
=> CPD-8052: shell out commands for ruby 3.1.2.

moonshot.gemspec
=> CPD-11158: bump activesupport version

lib/moonshot/command_line.rb, lib/moonshot/shell.rb, spec/spec_helper.rb
=> PC-23519 | moonshot spec tests are failing with Ruby 3.3.4
