moonshot.gemspec
- < 3.2.2 includes in activesupport json which breaks time formatting in JSON objects.
- 3.2.2 doesn't have a default locale, leading to uncaught i18n exception.
=> Require ruby-duration 3.2.3+ to avoid issues:

docs/example.md
> In this example we are going to use the resources of the sample directo This example assumes you ...
Sentence seems to stop, pull request fixes it.
=> Fixed typo in example usage of the moonshot library docs

lib/moonshot/stack_template.rb
Per the [AWS API reference](http://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_ValidateTemplate.html) the maximum length for TemplateBody is 51,200 bytes.  If a user has a very large base template then formatting with white space takes up precious bytes.  A user of moonshot should not have to compromise the readability of their template or code their own JSON minifier.
=> Minify stack template JSON to save bytes

lib/moonshot/artifact_repository/s3_bucket.rb
This allows multiple projects to use the same bucket for builds without matching versions overwriting each other. The prefix is optional, so it does not break backwards compatibility.
=> Added prefix for S3 artifact file name.

lib/moonshot/controller.rb
Sorry for posting this out of the blue, I just felt like this doesn't really need an issue or a previous discussion. Since documentation states there's a `pre_status` and a `post_status` method available for plugins, I fixed the controller accordingly.
=> Status plugins invocation fix

lib/moonshot/artifact_repository/s3_bucket.rb, moonshot.gemspec
Previously, files uploaded by other accounts were not accessible by the bucket owner.
For example, if we created deployments in our "production" account, they were unreadable in our "development" account.
=> CPD-885 Grant access to S3 artifacts created in other accounts.

lib/moonshot/build_mechanism/github_release.rb, lib/moonshot/build_mechanism/travis_deploy.rb, spec/moonshot/build_mechanism/github_release_spec.rb, spec/moonshot/build_mechanism/travis_deploy_spec.rb
These improvements accomplish two things:
- Allows a build to be re-run if it fails somewhere else during the process.
- Avoids an issue where a build does not show up on travis right away, I have seen this happen multiple times.
=> Build mechanism improvements

docs/example.md, docs/plugins.md, docs/user-guide/cli.md, lib/moonshot/cli.rb, lib/moonshot/controller.rb, lib/moonshot/controller_config.rb, lib/moonshot/stack.rb, lib/moonshot/stack_config.rb, spec/moonshot/stack_spec.rb
Implemented most of the features requested in #72.
By default the `ssh` command selects a random instance from the stack and opens an interactive SSH session. The instance ID, username, private key file and the command can be specified in the command line.
The `#ssh_command` and the `#ssh_options!` methods in `Moonshot::CLI` are there because with the help of them a user can implement custom SSH commands in their CLI tools pretty easily.
Example usage:
```ruby
desc :'sql-cli', 'Jump into mysql console on an instance.'
ssh_options!
def sql_cli
ssh_command('mysql -u blah')
end
```
=> SSH functionality

docs/mechanisms/deployment.md, lib/moonshot/deployment_mechanism/code_deploy.rb
This PR adds the ability for Moonshot to create and validate deployment groups containing multiple ASGs per my issue #93 ...  This PR also contains the fix from my previous PR ( #95 ).
=> Multiple ASGs in deployment group

lib/moonshot/build_mechanism/travis_deploy.rb, moonshot.gemspec, spec/moonshot/build_mechanism/travis_deploy_spec.rb
This resolves an issue where `travis logs` would continue to run even after the build had completed.
=> Use travis client rather than CLI to wait for the job to complete.

lib/moonshot/deployment_mechanism/code_deploy.rb
**Feature request**
I'd like the deployment group name to be configurable in order to support an admittedly unorthodox usage of Moonshot. This pull request adds that capability.
**Technique**
The unorthodox usage is to manage the CodeDeploy application in CloudFormation, using a single application for the stack and different deployment groups for the ASGs. This allows me to delete the entire stack (including the CodeDeploy stuff) outside of Moonshot if I choose to do so which is sometimes more convenient.
I have a ruby wrapper `bin/environment` that is only used for managing the infrastructure. I then have ruby wrappers for the API and the Worker tier at `bin/api` and `bin/worker` that are used for deploying code for the components. I could be doing this totally wrong, but I really like …
=> Allow the deployment group name to be configurable in order to support and alternate multi-ASG strategy

lib/moonshot/cli.rb, lib/moonshot/controller.rb, lib/moonshot/controller_config.rb, lib/moonshot/ssh_command_builder.rb, lib/moonshot/ssh_config.rb, lib/moonshot/ssh_target_selector.rb, lib/moonshot/stack.rb, lib/moonshot/stack_config.rb, spec/moonshot/build_mechanism/travis_deploy_spec.rb, spec/moonshot/ssh_spec.rb, spec/moonshot/stack_spec.rb
This patch removes all SSH logic from the stack, instead implementing a few new classes to handle the separate roles of building a command, choosing an instance to connect to and actually doing the connection (which lives in the Controller, for now).
This was needed while I was implementing #124, because the command execution and building were tightly coupled to the stack, and I need to be able to use the building logic without the choosing logic, and do so in a fork.
Includes a test update for Travis tests to reduce rspec runtime by 9 seconds.
=> Refactor SSH functionality.

lib/moonshot/stack.rb
Didn't catch these while reviewing #133, because they're used by plugins during creation. We do need better testing here.
=> Fixup a few Stack methods that parse JSON directly.

lib/moonshot/controller.rb, lib/moonshot/controller_config.rb, lib/moonshot/stack.rb, spec/moonshot/stack_spec.rb
* Updates tags on UpdateStack, as well as CreateStack.
* Uses two new tags: moonshot_application, moonshot_environment.
* Supports an additional tag for internal use, defaults to off.
Because this removes auto_prefix_stack, I'll wait to hear back on the RFC before merging this.
=> Fixes #99: Change Stack tagging.

.rubocop.yml, lib/moonshot.rb, lib/moonshot/commands/create.rb, lib/moonshot/commands/parameter_arguments.rb, lib/moonshot/commands/update.rb, lib/moonshot/controller.rb, lib/moonshot/controller_config.rb, lib/moonshot/parameter_collection.rb, lib/moonshot/parent_stack_parameter_loader.rb, lib/moonshot/resources.rb, lib/moonshot/stack.rb, lib/moonshot/stack_parameter.rb, lib/moonshot/stack_template.rb, spec/fixtures/answer1.yml, spec/fixtures/answer2.yml, spec/fixtures/create1.yml, spec/fixtures/empty1.yml, spec/fixtures/update1.yml, spec/fixtures/update2.yml, spec/moonshot/build_mechanism/github_release_spec.rb, spec/moonshot/build_mechanism/travis_deploy_spec.rb, spec/moonshot/commands/create_spec.rb, spec/moonshot/commands/update_spec.rb, spec/moonshot/controller_spec.rb, spec/moonshot/plugins_spec.rb, spec/moonshot/shell_spec.rb, spec/moonshot/stack_spec.rb, spec/spec_helper.rb
This starts to implement #184, minus the interactive gathering of parameters. Includes testing and I've done quite a bit of testing on my 1.x branch for our project.
=> Implement first pass at AWS-as-source-of-truth parameters management.

lib/moonshot.rb, lib/moonshot/always_use_default_source.rb, lib/moonshot/ask_user_source.rb, lib/moonshot/commands/parameter_arguments.rb, lib/moonshot/controller.rb, lib/moonshot/controller_config.rb, lib/moonshot/parent_stack_parameter_loader.rb, lib/moonshot/stack_parameter.rb, lib/moonshot/stack_template.rb, spec/moonshot/controller_spec.rb, spec/moonshot/plugins_spec.rb
Some of the improvements in this patch have lead me to a really simple implementation of a really complicated internal plugin we had that used KMS Keys to encrypt parameter values. I'll be putting up another patch to add this feature to core, as an example of how we can use the parameter collections and plugins as a sort of middleware model.
=> Add interactive prompting for missing parameters on create/update.

lib/moonshot/command.rb, lib/moonshot/commands/console.rb, spec/moonshot/command_spec.rb, spec/moonshot/commands/console_spec.rb, spec/spec_helper.rb
Unfortunately, I don't have the key needed for code climate, but it now needs to be run in travis.yml.
```
This usage of the Code Climate Test Reporter is now deprecated. Since version
1.0, we now require you to run `SimpleCov` in your test/spec helper, and then
run the provided `codeclimate-test-reporter` binary separately to report your
results to Code Climate.
More information here: https://github.com/codeclimate/ruby-test-reporter/blob/master/README.md
```
=> Fixes cli debug logging

lib/moonshot/ssh_config.rb
These variables not working after 0.7.7
=> Fix the usege of MOONSHOT_SSH_USER and MOONSHOT_SSH_KEY_FILE environment variables

docs/plugins.md, lib/moonshot/command_line_dispatcher.rb, lib/moonshot/deployment_mechanism/code_deploy.rb
This is used to implement --ignore-app-stop-failures for CodeDeploy.
=> Fixes #105: Add CLI hooks to mechanisms and plugins.

lib/plugins/encrypted_parameters.rb, lib/plugins/encrypted_parameters/kms_key.rb, lib/plugins/encrypted_parameters/parameter_encrypter.rb
Refactoring the `EncryptedParameters` plugin to be in the `Moonshot::Plugins` module instead of `Moonshot` to conform with its own documentation:
https://github.com/acquia/moonshot/blob/master/lib/plugins/encrypted_parameters.rb#L14
=> EncryptedParameters plugin should be in the Moonshot::Plugins module

lib/moonshot/command_line_dispatcher.rb, spec/moonshot/command_optional_argument_spec.rb
This patch allows us to use optional arguments on `execute` like this one:
```
moonshot reset [version] [options]
moonshot reset                   # for development version
moonshot reset my_custom_version # for custom version
```
=> Allow optional arguments for commands

lib/moonshot/command.rb, lib/moonshot/shell.rb
Testing moonshot 2.0.0 beta1 on xenial using default ruby version
of 2.3 and moonshot is unable to work due to command and shell not
requiring OptParse and Thor correctly.
This resolves #201
=> Optparse and Thor not required correctly

lib/moonshot/ssh_command.rb, lib/moonshot/ssh_target_selector.rb
`moonshot ssh` wasn't working properly in case of multiple ASGs.
=> Fix ssh command when using multiple ASGs

lib/moonshot/stack_asg_printer.rb
This fixes an issue when there's a standby instance in one of the ASGs.
```
$ moonshot status
┌─ CodeDeploy Application: app-dev-user
│
│ Application and Deployment Group are configured correctly.
│
└──
CloudFormation Stack app-dev-user exists.
undefined method `public_ip_address' for nil:NilClass
Did you mean?  public_send (at /home/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/moonshot-494af420cef0/lib/moonshot/stack_asg_printer.rb:117:in `instance_row')
```
=> Fix status command if there's a standby instance in the ASG

docs/mechanisms/deployment.md, lib/moonshot/deployment_mechanism/code_deploy.rb
This feature allows the user to specify an array of optional ASGs for `Moonshot::DeploymentMechanism::CodeDeploy`.
The application will be deployed to the ASGs listed here the same way as the `asg` parameter, but the deployment won't fail if the optional ASGs don't exist, `moonshot` will simply skip them.
We use this feature internally in our app, but it could be useful for someone else.
=> Added support for optional ASGs in CodeDeploy

lib/moonshot/stack_output_printer.rb
I essentially copied the parameter printer over because I like purdy output.
This raised a question though. Why do we [truncate the parameter output](https://github.com/acquia/moonshot/blob/master/lib/moonshot/stack_parameter_printer.rb#L21) at all? I see from the last commit that this was enlarged from 40 to 60, but I think that being able to read all of the parameters a stack was configured with, unadulterated, as being a good thing. I didn't port `format_value` across because it could render output values useless.
=> Sort and format stack output printer

lib/moonshot/stack.rb, spec/moonshot/stack_spec.rb
Updated create and update stack to support all possibile IAM
capabilities.
From AWS docs: If you have IAM resources, you can specify either capability. If you have IAM resources with custom names, you must specify CAPABILITY_NAMED_IAM. If you don't specify this parameter, this action returns an InsufficientCapabilities error.
=> Update capabilities to support named iam

lib/moonshot/change_set.rb, lib/moonshot/controller_config.rb
AWS sometimes fails to create a changeset in 30 seconds when we're running a `moonshot update`, causing our release jobs to fail.
The following has been implemented in this PR:
- Changeset wait time is now configurable, defaults to 90 seconds.
```moonfile.rb
Moonshot.config do |c|
...
c.changeset_wait_time = 120
end
```
- Slowed down science a bit since [other waiters seem to wait at least 5 seconds](https://github.com/aws/aws-sdk-ruby/blob/master/aws-sdk-core/apis/cloudformation/2010-05-15/waiters-2.json#L5) before repeating requests.
=> Added support for changing changeset wait time

lib/moonshot/commands/update.rb, lib/moonshot/controller.rb, spec/moonshot/controller_spec.rb
Adds a new --refresh-parameters flag for update calls allowing stacks
to refresh parent stack parameters if necessary
=> new --refresh-parameters flag for update

lib/moonshot/commands/parent_stack_option.rb, spec/moonshot/commands/create_spec.rb
Bug in the option parser where it was only pushing one
parent stack from the command line even through the config
loader would later loop over all parents provided.
=> Parent stacks command only allowing one parent

lib/moonshot/stack_asg_printer.rb
For compliance, among many other, reasons it is best practice to use a jump host to access remote networks.
Currently the output of `moonshot status` only shows the external IP of an instance, when present, which is impossible to use for ssh, when on that private network. Outputting the private IP makes it easier for an admin to find and connect to a valid instance in an ASG.
Please let me know if you'd prefer a different format for the output :)
=> Output the private IP regardless of an instance's public IP.

lib/plugins/backup.rb, spec/moonshot/plugins/backup_spec.rb
Buckets are specific to a region.  Currently, specifying a bucket in region A and then running moonshot in region B will fail to execute the backup.
=> Make it possible to specify the backup bucket region.

moonshot.gemspec
So, this was lulz. The published gem didn't contain any of the default files copied in to place with `moonshot new $foo`, with exception of `Moonfile.rb`
```
$ ls ~/.rvm/gems/ruby-2.3.3/gems/moonshot-2.0.0.beta2/lib/default/
Moonfile.rb
$
```
=> Add lib/default when building gem

docs/mechanisms/build.md, docs/plugins.md, docs/user-guide/cli.md, lib/moonshot/build_mechanism/github_release.rb, spec/moonshot/build_mechanism/github_release_spec.rb
Testing Steps:
==
1. cd moonshot/lib/default
2. check --help without GithubRelease plugin
```
moonshot deploy --help 
Usage: moonshot deploy VERSION
-v, --[no-]verbose               Show debug logging
-n, --environment=NAME           Which environment to operate on.
--[no-]interactive-logger    Enable or disable fancy logging
--[no-]interactive           Use interactive prompts.
```
3. register github plugin by update Moonfile.rb with below content
```
Moonshot.config do |c|
c.build_mechanism = GithubRelease.new('')
c.deployment_mechanism = CodeDeploy.new(asg: 'AutoScalingGroup')
end
```
4- check --help again 
```
moonshot deploy --help 
Usage: moonshot deploy VERSION
-v, --[no-]verbose               Show debug logging
-n, --environment=NAME           Which environment to operate on. …
```
=> CPD-1298 | As a cloud data engineer, I would to able to skip the SHA status check when building a release.

lib/moonshot/build_mechanism/github_release.rb
Testing Steps:
===
1. cd moonshot/lib/default
2. check --help without GithubRelease plugin
moonshot build --help 
```
moonshot build --help 
Usage: moonshot build VERSION
-v, --[no-]verbose               Show debug logging
-n, --environment=NAME           Which environment to operate on.
--[no-]interactive-logger    Enable or disable fancy logging
```
3. register github plugin by update Moonfile.rb with below content
```
Moonshot.config do |c|
c.build_mechanism = GithubRelease.new('')
c.deployment_mechanism = CodeDeploy.new(asg: 'AutoScalingGroup')
end
```
4- check --help again
```
Usage: moonshot build VERSION
-v, --[no-]verbose               Show debug logging
-n, --environment=NAME           Which environment to operate on.
--[no-]interactive-logger    Enable or disable fancy logging …
```
=> CPD-2350 | Add the skip_ci_status option to the github release mechanism in build command

lib/moonshot/build_mechanism/github_release.rb, spec/moonshot/commands/build_spec.rb
```
moonshot build --help 
Usage: moonshot build VERSION
-v, --[no-]verbose               Show debug logging
-n, --environment=NAME           Which environment to operate on.
--[no-]interactive-logger    Enable or disable fancy logging
-s, --[no-]skip-ci-status        Skips checks on CI jobs
```
Testing command:
`rspec   spec/moonshot/commands/build_spec.rb`
this PR is tested and working perfect
```
[ ✓ ] [ 0m 22s ] Clone git@github.com:hmagdy/cloud-database-api.git to release-cloud-database-api-1.2.320170831-23703-i8ucvg                 
[ ✓ ] [ 0m 1s ] Checkout 4f43bfbe7edbe6cb950326ad60571a4d85e504f8                                                                            
[ ✓ ] [ 0m 1s ] rsync -a --include='vendor/bundle/***' --include='vendor*/' --exclude='*' …
```
=> CPD-1298 | As a cloud data engineer, I would like to able to skip the SHA status check when building a release.

lib/moonshot/command_line.rb
Sort the commands by name, so they appear in alphabetical order in the help output.
=> sort commands

lib/moonshot/controller_config.rb, lib/moonshot/stack.rb, spec/moonshot/stack_spec.rb
I hit the [51,200 bytes size limitation](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cloudformation-limits.html) of the template body.
One of the suggested resolutions there is to upload the template to an S3 bucket. This patch makes moonshot to be able to do that.
I added a new configuration option: `template_s3_bucket`. If it's set, moonshot will always upload the local template to that bucket then use its URL in the API calls.
=> Added ability to push CF template to S3

moonshot.gemspec
Gem `require_all` 2.0.0 breaks Moonshot with `LoadError` because of a change introduced in https://github.com/jarmo/require_all/pull/24.
```
$ bundle list | grep require_all
* require_all (2.0.0)
$ bundle exec moonshot new test
bundler: failed to load command: moonshot (/Users/csibar/workspaces/acquia/require_all_fail/vendor/ruby/2.3.0/bin/moonshot)
RequireAll::LoadError: Could not require /Users/csibar/workspaces/acquia/require_all_fail/vendor/ruby/2.3.0/bundler/gems/moonshot-512b19628963/lib/moonshot/artifact_repository/s3_bucket.rb (uninitialized constant Moonshot::ResourcesHelper). Please require the necessary files
/Users/csibar/workspaces/acquia/require_all_fail/vendor/ruby/2.3.0/gems/require_all-2.0.0/lib/require_all.rb:102:in `rescue in block in require_all' …
```
=> Pin require_all version to ~>1.5.0

lib/moonshot/stack.rb
Doctor fails on master HEAD because it sends all parameters of a stack to the template validation call. `parameters` on line 324 is actually a function call (see line 83) which returns the parameters of a stack. The template url/body was added to this hash and sent to AWS on line 328 in `validate_template`. Since that call expects only the url or the body (https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/CloudFormation/Client.html#validate_template-instance_method), it failed like this:
```
11:51 master $ bundle exec moonshot doctor
Stack
✓ CloudFormation template found at 'xxx.json'.
✗ Invalid CloudFormation template!
parameter validator found 33 errors:
- unexpected value at params["xxx"]
- unexpected value at params["xxx"]
- unexpected value at params["xxx"]
...
```
This proposed …
=> Fixed CloudFormation template check in 'doctor'.

lib/moonshot/build_mechanism/github_release.rb, lib/moonshot/build_mechanism/version_proxy.rb
This resolves an issue where the build command fails when passing a command line argument provided by one of the build mechanisms configured in the version proxy mechanism. It does however present an issue that I've documented in the code here.
=> Expose build CLI options for version proxy mechanisms.

docs/plugins/rotate_asg_instances.md, lib/plugins/rotate_asg_instances.rb, lib/plugins/rotate_asg_instances/asg.rb, spec/moonshot/plugins/asg.rb
Change: minor
Purpose: feature
1. For pointing the changes for local environment of moonshot gem: [How to specify local Ruby gems in your Gemfile](https://rossta.net/blog/how-to-specify-local-ruby-gems-in-your-gemfile.html)
2. Once the above step is up and working, include the plugin in cloud-database-worker repo in Moonfile.rb by adding `c.plugins << Moonshot::Plugins::RotateAsgInstances.new` to the file.
3. Update the AMIMap key in `cdb-worker.json` and change the AMIs.
4. Run `cd cloud-database-worker && bundle exec moonshot update`
5. Open the aws console and go to `CloudFormation > Stacks > cdb-worker-dev-#{stack_name}` where stack_name is your worker stack.
6. Go to the ASG of the stack and check the old instances are removed and new instances are attached with the updated launch …
=> CPD-183: Added ASG rotation plugin.

docs/plugins/rotate_asg_instances.md, lib/moonshot/ssh_command_builder.rb, lib/moonshot/ssh_config.rb, lib/moonshot/ssh_fork_executor.rb, lib/plugins/rotate_asg_instances.rb, lib/plugins/rotate_asg_instances/asg.rb, lib/plugins/rotate_asg_instances/ssh.rb, spec/moonshot/plugins/rotate_asg_instances/asg_spec.rb, spec/moonshot/plugins/rotate_asg_instances/ssh_spec.rb, spec/moonshot/plugins/rotate_asg_instances_spec.rb, spec/moonshot/ssh_spec.rb
Change: minor
Purpose: feature
**Release test**: [#511](https://cloud-data.jenkins.r53.ahdev.co/job/rls-test-dev/511) ✅
**System test**: [#1081](https://cloud-data.jenkins.r53.ahdev.co/job/sys-test-dev/1081) ✅ 
**Manual Review**: [Review document](https://confluence.acquia.com/x/vwnPBg)
- [cloud-database-api](https://github.com/acquia/cloud-database-api/pull/1739)
- [cloud-database-worker](https://github.com/acquia/cloud-database-worker/pull/1020)
Added a pre-check for verifying the plugin can work before attempting to rotate AutoScalingGroup instances.
=> CPD-183: Added pre-check to plugin

lib/plugins/rotate_asg_instances/asg.rb
Change: minor
Purpose: maintenance
Manual review steps:
1. Get a worker stack and make sure the min instances is 2 or more else update it.
2. Make a trivial update to launch config, updating the ami id is a good example.
3. Issue stack update using moonshot
`moonshot update -n STACK_NAME`
4. while the first instance is being rotated by the rotation plugin, detach the other instance.
5. As the plugin moves forward and tries to rotate the other instance it raises error.
6. Update the moonshot gem to use code from this PR.
7. Repeat steps 1 through 4. It should not raise an error
=> CPD-6009: Rescue and continue if the instance is already detached

lib/moonshot/commands/create.rb, lib/moonshot/controller_config.rb, lib/moonshot/stack.rb, spec/moonshot/commands/create_spec.rb, spec/moonshot/stack_spec.rb
Using custom CF template
```
{
"Resources": {
"HelloBucket": {
"Type": "AWS::S3::Bucket"
}
}
}
```
Create options
```
➜ cloud-database-api ruby-2.7.3 (CPD-7518-fix) ✗ bundle exec moonshot help create                                              <aws:cloudservicesdev>
Using the Central Model for authentication
Version 2 of the Ruby SDK will enter maintenance mode as of November 20, 2020. To continue receiving service updates and new features, please upgrade to Version 3. More information can be found here: https://aws.amazon.com/blogs/developer/deprecation-schedule-for-aws-sdk-for-ruby-v2/
Using the Central Model for authentication
Usage: moonshot create [options]
-v, --[no-]verbose               Show debug logging
-n, --environment=NAME           Which environment to operate on. …
```
=> CPD-7518: Add tags option to create command.

lib/moonshot/build_mechanism/github_release.rb, spec/moonshot/build_mechanism/github_release_spec.rb
**Motivation**
(https://backlog.acquia.com/browse/CPD-8183)
=> CPD-8183: use correct command to validate hub authorization

lib/moonshot/tools/asg_rollout/asg.rb, moonshot.gemspec
**Motivation**
```
[cloudservicesdev|hosting-dev:prasan4] ~/git/hosting-api$ hosting-api rollout-launch-configuration --skip-hooks
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
Using the Central Model for authentication
[ ✓ ] [ 0m 4s ] Increased MaxSize/DesiredCapacity by 1.                                                                                                                                     
[ ✓ ] [ 0m 12s ] A wild i-091b8aa01f8b901ff appears!                                                                                                                                        
[ | ] [ 0m 0s ] Waiting for i-091b8aa01f8b901ff to be …
```
=> PC-17819 | Fix HAPI Errors related to Loadbalancing

lib/moonshot/commands/create.rb, lib/moonshot/commands/tag_arguments.rb, lib/moonshot/commands/update.rb, lib/moonshot/controller_config.rb, lib/moonshot/stack.rb, lib/plugins/encrypted_parameters.rb, lib/plugins/encrypted_parameters/kms_key.rb, spec/moonshot/commands/create_spec.rb, spec/moonshot/commands/update_spec.rb, spec/moonshot/stack_spec.rb
=> ORCH-11235 | Port upstream kms tagging changes to 2.0.0.beta6

lib/moonshot.rb, lib/moonshot/change_set.rb, moonshot.gemspec
**Motivation**
FIPS endpoint is only supported from aws-sdk v3 onwards so we have to upgrade the gem from v2 to v3. 
Updates aws-sdk gem to v3
N/A
N/A
=> CPD-8525 | When in US regions, the api and worker should use AWS FIPS endpoints where available
